package pe.egcc.casosapp.view;

import javax.swing.JInternalFrame;

/**
 *
 * @author Gustavo Coronel Castillo
 * @blog gcoronelc.blogspot.com
 * @email gcoronelc@gmail.com
 */
public class FormularioMDI extends javax.swing.JFrame {

  public FormularioMDI() {
    initComponents();
    this.setExtendedState(MAXIMIZED_BOTH);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jToolBar1 = new javax.swing.JToolBar();
    btnPago = new javax.swing.JButton();
    jSeparator1 = new javax.swing.JToolBar.Separator();
    btnPromedio = new javax.swing.JButton();
    jSeparator2 = new javax.swing.JToolBar.Separator();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jSeparator3 = new javax.swing.JToolBar.Separator();
    btnSalir = new javax.swing.JButton();
    desktopPane = new javax.swing.JDesktopPane();
    menuBar = new javax.swing.JMenuBar();
    menuArchivo = new javax.swing.JMenu();
    menuArchivoSalir = new javax.swing.JMenuItem();
    menuViaExitos = new javax.swing.JMenu();
    menuViaExitosPago = new javax.swing.JMenuItem();
    menuSobrecarga = new javax.swing.JMenu();
    menuSobrecargaPromedio = new javax.swing.JMenuItem();
    menuAlcanceClase = new javax.swing.JMenu();
    menuAlcanceClaseFactorial = new javax.swing.JMenuItem();
    menuAlcanceClaseMcdMcm = new javax.swing.JMenuItem();
    menuAlcanceClaseFibonacci = new javax.swing.JMenuItem();
    menuAlcanceClasePrimo = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("CASOS");

    jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
    jToolBar1.setFloatable(false);
    jToolBar1.setRollover(true);

    btnPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/casosapp/img/Money.png"))); // NOI18N
    btnPago.setToolTipText("Calculo de pago.");
    btnPago.setFocusable(false);
    btnPago.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnPago.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnPago.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPagoActionPerformed(evt);
      }
    });
    jToolBar1.add(btnPago);
    jToolBar1.add(jSeparator1);

    btnPromedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/casosapp/img/calculadora.png"))); // NOI18N
    btnPromedio.setToolTipText("Promedio");
    btnPromedio.setFocusable(false);
    btnPromedio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnPromedio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnPromedio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPromedioActionPerformed(evt);
      }
    });
    jToolBar1.add(btnPromedio);
    jToolBar1.add(jSeparator2);

    jButton3.setText("Factorial");
    jButton3.setFocusable(false);
    jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton3);

    jButton4.setText("jButton4");
    jButton4.setFocusable(false);
    jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton4);

    jButton5.setText("jButton5");
    jButton5.setFocusable(false);
    jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton5);

    jButton6.setText("jButton6");
    jButton6.setFocusable(false);
    jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jButton6);
    jToolBar1.add(jSeparator3);

    btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/casosapp/img/exit2.png"))); // NOI18N
    btnSalir.setToolTipText("Salir de la aplicación.");
    btnSalir.setFocusable(false);
    btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSalirActionPerformed(evt);
      }
    });
    jToolBar1.add(btnSalir);

    menuArchivo.setText("Archivo");

    menuArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
    menuArchivoSalir.setText("Salir");
    menuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuArchivoSalirActionPerformed(evt);
      }
    });
    menuArchivo.add(menuArchivoSalir);

    menuBar.add(menuArchivo);

    menuViaExitos.setText("Vía Exitos");

    menuViaExitosPago.setText("Pago");
    menuViaExitosPago.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuViaExitosPagoActionPerformed(evt);
      }
    });
    menuViaExitos.add(menuViaExitosPago);

    menuBar.add(menuViaExitos);

    menuSobrecarga.setText("Sobrecarga");

    menuSobrecargaPromedio.setText("Promedio");
    menuSobrecargaPromedio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuSobrecargaPromedioActionPerformed(evt);
      }
    });
    menuSobrecarga.add(menuSobrecargaPromedio);

    menuBar.add(menuSobrecarga);

    menuAlcanceClase.setText("Alcance de Clase");

    menuAlcanceClaseFactorial.setText("Factorial");
    menuAlcanceClase.add(menuAlcanceClaseFactorial);

    menuAlcanceClaseMcdMcm.setText("MCD y MCM");
    menuAlcanceClase.add(menuAlcanceClaseMcdMcm);

    menuAlcanceClaseFibonacci.setText("Fibonacci");
    menuAlcanceClase.add(menuAlcanceClaseFibonacci);

    menuAlcanceClasePrimo.setText("Primo");
    menuAlcanceClase.add(menuAlcanceClasePrimo);

    menuBar.add(menuAlcanceClase);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
      .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void menuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoSalirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_menuArchivoSalirActionPerformed

  private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_btnSalirActionPerformed

  private void menuViaExitosPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuViaExitosPagoActionPerformed
    cargarFormulario(PagoView.class);
  }//GEN-LAST:event_menuViaExitosPagoActionPerformed

  private void menuSobrecargaPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobrecargaPromedioActionPerformed
    cargarFormulario(PromedioView.class);
  }//GEN-LAST:event_menuSobrecargaPromedioActionPerformed

  private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
    cargarFormulario(PagoView.class);
  }//GEN-LAST:event_btnPagoActionPerformed

  private void btnPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedioActionPerformed
    cargarFormulario(PromedioView.class);
  }//GEN-LAST:event_btnPromedioActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FormularioMDI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnPago;
  private javax.swing.JButton btnPromedio;
  private javax.swing.JButton btnSalir;
  private javax.swing.JDesktopPane desktopPane;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JToolBar.Separator jSeparator1;
  private javax.swing.JToolBar.Separator jSeparator2;
  private javax.swing.JToolBar.Separator jSeparator3;
  private javax.swing.JToolBar jToolBar1;
  private javax.swing.JMenu menuAlcanceClase;
  private javax.swing.JMenuItem menuAlcanceClaseFactorial;
  private javax.swing.JMenuItem menuAlcanceClaseFibonacci;
  private javax.swing.JMenuItem menuAlcanceClaseMcdMcm;
  private javax.swing.JMenuItem menuAlcanceClasePrimo;
  private javax.swing.JMenu menuArchivo;
  private javax.swing.JMenuItem menuArchivoSalir;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenu menuSobrecarga;
  private javax.swing.JMenuItem menuSobrecargaPromedio;
  private javax.swing.JMenu menuViaExitos;
  private javax.swing.JMenuItem menuViaExitosPago;
  // End of variables declaration//GEN-END:variables

  private void cargarFormulario(Class<?> aClass) {
    try {
      // Variable de control
      JInternalFrame view = null;
      // Buscar instancia
      for(JInternalFrame f: desktopPane.getAllFrames()){
        if(aClass.isInstance(f)){
          view = f;
          break;
        }
      }
      // Crear la instancia
      if(view == null){
        view =(JInternalFrame) Class.forName(aClass.getName()).newInstance();
        desktopPane.add(view);
        view.setVisible(true);
      }
      // Activar el formulario
      view.setSelected(true);
    } catch (Exception e) {
    }
  }

}
